### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by gtrak** [mirage/alcotest#221] opened 2020-02-26 19:21 UTC
We had a test with a massive number of test cases, and alcotest blew up on opening a log file.  My suspicion is that these log files are not closed properly until the test suite has finished.

At the time, I had ulimit of open-files at 1024, which was way too low for our development environment in other cases, but I think it's worth bringing attention here.

Alcotest blew the limit on the 1013'th log file.
```
[OK]                all        1011   some test
[OK]                all        1012   some other test
 ...                all        1013   some other other test: internal error, uncaught exception:
                                Unix.Unix_error(Unix.EMFILE, "open", "/home/gary/project/_build/_tests/35B882A8-76BD-4347-82A4-84DDC57A1E0A/all.1013.output")
                                Raised by primitive operation at file "src/alcotest.ml", line 309, characters 22-70
                                Called from file "src/alcotest.ml", line 296, characters 15-24
                                Called from file "list.ml", line 82, characters 20-23
                                Called from file "list.ml", line 82, characters 32-39
                                Called from file "list.ml", line 82, characters 32-39
```

We're running on 0.8.5:
https://github.com/mirage/alcotest/blob/0.8.5/src/alcotest.ml#L296

**Comment by gtrak** [comment] 2020-02-26 19:50
We get a similar issue on 1.0.1, without the List.ml stack:
```
 ...                all        1013   some test: internal error, uncaught exception:
                                Unix.Unix_error(Unix.EMFILE, "open", "/home/gary/project/_build/_tests/20F89D5C-1BEA-4424-BBBD-761CC3D6350F/all.1013.output")
                                Raised by primitive operation at file "src/alcotest/core.ml", line 377, characters 24-74
                                Called from file "src/alcotest/core.ml", line 349, characters 4-13
                                Called from file "src/alcotest/monad.ml", line 66, characters 22-26
                                Called from file "src/alcotest/core.ml", line 429, characters 4-29
                                Called from file "src/alcotest/core.ml", line 477, characters 14-33
                                Called from file "src/alcotest/core.ml", line 545, characters 10-37
                                Called from file "src/alcotest/cli.ml", line 73, characters 4-128
                                Called from file "cmdliner_term.ml", line 25, characters 19-24
                                Called from file "cmdliner.ml", line 117, characters 32-39
Uncaught exception:
  Alcotest__Core.Make(M).Test_error
Raised at file "src/alcotest/cli.ml", line 267, characters 18-34
Called from file "src/alcotest/cli.ml", line 272, characters 4-141
Called from file "project/src/test_runners.ml", line 28, characters 2-131
Called from file "project/test/the_test_we_are_running.ml", line 73, characters 2-1023
```

**Comment by icristescu** [comment] 2020-02-27 12:36
Thanks for reporting this. 

When I run several tests and print the fd at the beginning of each test, I can only see the ones corresponding to the current test case. 
Can you check what are the file descriptors opened by your process? Maybe print them just before the test case that fail.

**Comment by CraigFe** [comment] 2021-01-18 12:38
I've tried to reproduce this by running ~100,000 tests with captured logs, and found that the number of open FDs was stable.

It's very possible that this is due to Alcotest, but without a reproduction / more information about which FDs are leaking it's difficult to suggest a fix; closing for now.

**Closed by CraigFe** 2021-01-18 12:38 UTC
