### ISSUE TITLE
Allow running tests concurrently in alcotest-lwt

### ISSUE THREAD

**Issue by MisterDA** [mirage/alcotest#343] opened 2022-02-28 08:47 UTC
Lwt ad-hoc testing suite has the nice feature that all its tests can run concurrently in the Lwt event loop. Some tests can be marked sequential and are run, well, sequentially, after all the concurrent tests have executed. It'd be nice if alcotest-lwt could provide the same. I'm not sure which default behaviour would be best, sequential or concurrent (Lwt's tests default).

**Comment by CraigFe** [comment] 2022-02-28 09:13
Duplicate of https://github.com/mirage/alcotest/issues/177. Feel free to re-open if you think otherwise :-)

**Closed by CraigFe** 2022-02-28 09:13 UTC
